Feature/70 overwrite -> develop
astrochun/Zcalbase_gal pull request #74
Opened 2021-01-22 00:15 UTC by Reagen

Includes Issue #70

2021-01-23 22:19 UTC, astrochun commented on analysis/deep2_r23_o32/general.py
>      # tab1.write(fitspath_ini+'get_det3_table.fit', format = 'fits', overwrite = True)
```suggestion
```

2021-01-23 22:19 UTC, astrochun commented on analysis/deep2_r23_o32/general.py
>      # tab1.write(fitspath_ini+'get_det3_table.fit', format = 'fits', overwrite = True)
Let's remove this unused line.

2021-01-23 22:28 UTC, astrochun requested changes
This looks good. Just one minor change.

2021-01-24 17:56 UTC, Reagen reviewed
Made the change

2021-01-26 04:25 UTC, astrochun approved these changes
Great. I'll go ahead and merge.

2021-01-26 04:26 UTC, merged